language: cpp

git:
  submodules: false

compiler:
    - gcc
    - clang

before_install:
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule init
    - git submodule sync
    - git submodule update

install:
    - sudo apt-get install libboost-all-dev libbz2-dev libssl-dev python-dev uuid-dev
    - Boost/install $(lsb_release -cs)

script:
    - ./build toolset=$CC -q

matrix:
    allow_failures:
        - compiler: gcc
