language: cpp
sudo: required
dist: xenial

compiler:
    - gcc
    - clang

env:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

cache:
  directories:
    boost-cache

install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y ninja-build g++-8

script:
    - mkdir build.tmp && cd build.tmp
    - 'if [ "$CXX" = "g++" ]; then export CC=gcc-8; export CXX=g++-8; fi'
    - git clone https://github.com/KayEss/fost-base.git
    - git clone https://github.com/KayEss/fost-boost.git
    - git clone https://github.com/KayEss/fost-crypto.git
    - git clone https://github.com/KayEss/fost-internet.git
    - git clone https://github.com/KayEss/fost-libpq.git PostgreSQL
    - sed -i 's/git@github.com:/https:\/\/github.com\//' PostgreSQL/.gitmodules
    - cd PostgreSQL && git submodule update --init --recursive && cd ..
    - git clone https://github.com/KayEss/fost-postgres.git
    - git clone https://github.com/KayEss/fost-web.git
    - git clone https://github.com/KayEss/f5-cord.git
    - git clone https://github.com/KayEss/f5-threading.git
    - ln -s ../../boost-cache fost-boost/boost
    - cp ../.travis.CMakeLists.txt CMakeLists.txt
    - cmake . -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -G Ninja
    - ninja
    - ninja check

